apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "common.names.fullname" . }}
data:
  config.json: |
    {
        "log": {
            "level": "{{ .Values.logLevel }}",
            "timestamp": true
        },
        "dns": {
            "servers": [
                {
                    "tag": "dns_proxy",
                    "address": "https://8.8.8.8/dns-query",
                    "address_resolver": "dns_resolver",
                    "strategy": "ipv4_only",
                    "detour": "proxy"
                },
                {
                    "tag": "dns_direct",
                    "address": "https://dns.alidns.com/dns-query",
                    "address_resolver": "dns_resolver",
                    "strategy": "ipv4_only",
                    "detour": "direct"
                },
                {
                    "tag": "dns_resolver",
                    "address": "223.5.5.5",
                    "detour": "direct"
                },
                {
                    "tag": "dns_block",
                    "address": "rcode://success"
                }
            ],
            "rules": [
                {
                    "outbound": "any",
                    "server": "dns_resolver"
                },
                {
                    "rule_set": "geosite-geolocation-!cn",
                    "server": "dns_proxy"
                },
                {
                    "rule_set": "geosite-cn",
                    "server": "dns_direct"
                }
            ],
            "final": "dns_direct"
        },
        "route": {
            "rule_set": [
                {
                    "tag": "geosite-geolocation-!cn",
                    "type": "remote",
                    "format": "binary",
                    "url": "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-geolocation-!cn.srs",
                    "download_detour": "proxy"
                },
                {
                    "tag": "geoip-cn",
                    "type": "remote",
                    "format": "binary",
                    "url": "https://raw.githubusercontent.com/SagerNet/sing-geoip/rule-set/geoip-cn.srs",
                    "download_detour": "proxy"
                },
                {
                    "tag": "geosite-cn",
                    "type": "remote",
                    "format": "binary",
                    "url": "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-cn.srs",
                    "download_detour": "proxy"
                }
            ],
            "rules": [
                {{- if .Values.routeRules }}
                {{- $routeRules := trim .Values.routeRules }}
                {{- printf "%s," $routeRules | nindent 16 }}
                {{- end }}
                {
                    "protocol": "dns",
                    "outbound": "dns-out"
                },
                {
                    "type": "logical",
                    "mode": "and",
                    "rules": [
                    {
                        "rule_set": "geoip-cn",
                        "invert": true
                    },
                    {
                        "rule_set": "geosite-geolocation-!cn"
                    }
                    ],
                    "outbound": "proxy"
                },
                {
                    "type": "logical",
                    "mode": "and",
                    "rules": [
                    {
                        "rule_set": "geoip-cn"
                    },
                    {
                        "rule_set": "geosite-cn"
                    }
                    ],
                    "outbound": "direct"
                },
                {
                    "rule_set": "geoip-cn",
                    "outbound": "direct"
                },
                {
                    "ip_is_private": true,
                    "outbound": "direct"
                }
            ],
            "final": "direct",
            "auto_detect_interface": true
        },
        "inbounds": [
            {
            "type": "mixed",
            "listen": "::",
            "listen_port": 7890
            }
        ],
        "outbounds": [
            {{- $tags := list -}}
            {{- range .Values.outbound -}}
            {{- $tags = append $tags .tag -}}
            {{- toPrettyJson . | nindent 12 -}},
            {{- end }}
            {
                "tag": "proxy",
                "type": "selector",
                "outbounds": {{ toJson $tags }},
                "default": "{{ first $tags }}",
                "interrupt_exist_connections": false
            },
            {
                "type": "direct",
                "tag": "direct"
            },
            {
                "type": "block",
                "tag": "block"
            },
            {
                "type": "dns",
                "tag": "dns-out"
            }
        ],
        "experimental": {
            "cache_file": {
                "enabled": true,
                "path": "cache.db"
            },
            "clash_api": {
                "external_controller": "0.0.0.0:9090",
                "external_ui": "ui",
                "external_ui_download_detour": "proxy"
            }
        }
    }