apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
      {{- include "common.labels.matchLabels" . | nindent 4 }}
  ports:
    - name: sing-box
      protocol: TCP
      port: 7890
      targetPort: 7890
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
