apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "common.names.fullname" . }}-ui
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.service.ui.type }}
  selector:
      {{- include "common.labels.matchLabels" . | nindent 4 }}
  ports:
    - name: sing-box
      protocol: TCP
      port: 9090
      targetPort: 9090
      {{- if eq .Values.service.ui.type "NodePort" }}
      nodePort: {{ .Values.service.ui.nodePort }}
      {{- end }}
