replicaCount: 1

service:
  proxy:
    type: ClusterIP
    # type: NodePort
    # nodePort: 30001
  ui:
    type: ClusterIP
    # type: NodePort
    # nodePort: 30002

# 默认情况下, sing-box 将日志打印到 STDOUT
# 日志等级，可选值：trace debug info warn error fatal panic。
logLevel: error

outbound:
  # - tag: ""
  #   type: "hysteria2"
  #   server: ""
  #   server_port: 443
  #   password: ""
  #   tls:
  #     enabled: true
  #     alpn:
  #       - "h3"