apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "common.names.fullname" . }}
data:
  nanomq.conf: |
    mqtt {
        property_size = 32
        max_packet_size = 10KB
        max_mqueue_len = 2048
        retry_interval = 10s
        keepalive_multiplier = 1.25
        
        max_inflight_window = 2048
        max_awaiting_rel = 10s
        await_rel_timeout = 10s
    }

    listeners.tcp {
        bind = "0.0.0.0:1883"
    }

    listeners.ws {
        bind = "0.0.0.0:8083/mqtt"
    }

    http_server {
        port = 8081
        limit_conn = 2
        username = admin
        password = public
        auth_type = basic
        jwt {
            public.keyfile = "/etc/certs/jwt/jwtRS256.key.pub"
        }
    }

    log {
        to = [file, console]
        level = warn
        dir = "/tmp"
        file = "nanomq.log"
        rotation {
            size = 10MB
            count = 5
        }
    }

    auth {
        allow_anonymous = false
        no_match = deny
        deny_action = ignore
        
        cache = {
            max_size = 32
            ttl = 1m
        }
        
        password = {include "/etc/nanomq/nanomq_pwd.conf"}
        acl = {include "/etc/nanomq/nanomq_acl.conf"}
    }


  nanomq_pwd.conf: |
    {{- range .Values.users -}}
    {{- printf "%s: %s " .username .password | nindent 4 -}}
    {{- end }}
  
  nanomq_acl.conf: |
    rules = [
      {{- range .Values.acl -}}
      {{- .data | nindent 6 -}}
      {{- end }}
    ]