apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
  ports:
    - name: kkfileview
      protocol: TCP
      port: 8012
      targetPort: 8012