apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "common.names.fullname" . }}-proxy
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: NodePort
  selector:
      {{- include "common.labels.matchLabels" . | nindent 4 }}
  ports:
    - name: clash-proxy
      protocol: TCP
      port: 7890
      targetPort: 7890
      nodePort: {{ .Values.proxy.nodePort }}
