apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "common.names.fullname" . }}-api
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
      {{- include "common.labels.matchLabels" . | nindent 4 }}
  ports:
    - name: clash-api
      protocol: TCP
      port: 9090
      targetPort: 9090