replicaCount: 1

auth:
  rootPassword: abc123

mycnf: |
  [mysqld]
  max_connections=400
  lower_case_table_names=1
  innodb_buffer_pool_size=512M
  sync_binlog=0
  binlog_expire_logs_seconds=604800

config:
  timezone: Asia/Shanghai
  database:

service:
  type: ClusterIP
  # type: NodePort
  # nodePort: 30011

backup:
  enabled: false
  schedule: "0 2 * * *"
  saveFileNum: 5

pvc:
  data:
    storageClassName: longhorn
    storage: 5Gi
  backup:
    storageClassName: longhorn
    storage: 15Gi