replicaCount: 1

auth:
  rootPassword: abc123

config:
  maxConnections: 400
  timezone: Asia/Shanghai
  expireLogsDays: 7
  database: 

service: 
  type: ClusterIP
  # type: NodePort
  # nodePort: 30011

backup:
  enabled: false
  schedule: "0 2 * * *"
  saveFileNum: 5

pvc:
  data:
    storageClassName: longhorn
    storage: 5Gi
  backup:
    storageClassName: longhorn
    storage: 15Gi