apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  serviceName: "{{ include "common.names.fullname" . }}-headless"
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/mysql-cm.yaml") . | sha256sum }}
      labels:
        {{- include "common.labels.matchLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mysql
          image: mysql:{{ .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: {{ .Values.config.timezone }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.auth.rootPassword | quote }}
            {{- if .Values.config.database }}
            - name: MYSQL_DATABASE
              value: {{ .Values.config.database }}
            {{- end }}
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: config
              mountPath: /etc/mysql/conf.d
              readOnly: true
            - name: data
              mountPath: /var/lib/mysql
            {{- if .Values.backup.enabled }}  
            - name: backup
              mountPath: /backup  
            {{- end }}    
      volumes:
        - name: config
          configMap:
            name: {{ include "common.names.fullname" . }}
        {{- if .Values.backup.enabled }}   
        - name: backup
          persistentVolumeClaim:
            claimName: backup-{{ include "common.names.fullname" . }}
        {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.pvc.data.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.pvc.data.storage }}
